//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        ///  
        public static string About
        {
            get
            {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }

        public static string Add
        {
            get
            {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        public static string AddDepartment
        {
            get
            {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }

        public static string AddProfessor
        {
            get
            {
                return ResourceManager.GetString("AddProfessor", resourceCulture);
            }
        }

        public static string Address
        {
            get
            {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string AddStudent
        {
            get
            {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }

        public static string AddSubject
        {
            get
            {
                return ResourceManager.GetString("AddSubject", resourceCulture);
            }
        }

        public static string And
        {
            get
            {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }

        public static string AverageGrade
        {
            get
            {
                return ResourceManager.GetString("AverageGrade", resourceCulture);
            }
        }

        public static string BirthDate
        {
            get
            {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }

        public static string Calling
        {
            get
            {
                return ResourceManager.GetString("Calling", resourceCulture);
            }
        }

        public static string Cancel
        {
            get
            {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        public static string cannotBe
        {
            get
            {
                return ResourceManager.GetString("cannotBe", resourceCulture);
            }
        }

        public static string City
        {
            get
            {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }

        public static string Close
        {
            get
            {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        public static string ComparingTwo
        {
            get
            {
                return ResourceManager.GetString("ComparingTwo", resourceCulture);
            }
        }

        public static string Confirmation
        {
            get
            {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }

        public static string Country
        {
            get
            {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        public static string Date
        {
            get
            {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }

        public static string DateOfGrading
        {
            get
            {
                return ResourceManager.GetString("DateOfGrading", resourceCulture);
            }
        }

        public static string delDep
        {
            get
            {
                return ResourceManager.GetString("delDep", resourceCulture);
            }
        }

        public static string Delete
        {
            get
            {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string DeleteConfirmation
        {
            get
            {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }

        public static string DeleteGrade
        {
            get
            {
                return ResourceManager.GetString("DeleteGrade", resourceCulture);
            }
        }

        public static string delGrade
        {
            get
            {
                return ResourceManager.GetString("delGrade", resourceCulture);
            }
        }

        public static string delGradeWarning
        {
            get
            {
                return ResourceManager.GetString("delGradeWarning", resourceCulture);
            }
        }

        public static string delProf
        {
            get
            {
                return ResourceManager.GetString("delProf", resourceCulture);
            }
        }

        public static string delStudent
        {
            get
            {
                return ResourceManager.GetString("delStudent", resourceCulture);
            }
        }

        public static string delStudWarning
        {
            get
            {
                return ResourceManager.GetString("delStudWarning", resourceCulture);
            }
        }

        public static string delSub
        {
            get
            {
                return ResourceManager.GetString("delSub", resourceCulture);
            }
        }

        public static string DepartmentDetails
        {
            get
            {
                return ResourceManager.GetString("DepartmentDetails", resourceCulture);
            }
        }

        public static string DepartmentId
        {
            get
            {
                return ResourceManager.GetString("DepartmentId", resourceCulture);
            }
        }

        public static string Departments
        {
            get
            {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }

        public static string Ects
        {
            get
            {
                return ResourceManager.GetString("Ects", resourceCulture);
            }
        }

        public static string Edit
        {
            get
            {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string Email
        {
            get
            {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }

        public static string English
        {
            get
            {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }

        public static string enrolled
        {
            get
            {
                return ResourceManager.GetString("enrolled", resourceCulture);
            }
        }

        public static string EnrollmentYear
        {
            get
            {
                return ResourceManager.GetString("EnrollmentYear", resourceCulture);
            }
        }

        public static string File
        {
            get
            {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }

        public static string FinancialAid
        {
            get
            {
                return ResourceManager.GetString("FinancialAid", resourceCulture);
            }
        }

        public static string FirstName
        {
            get
            {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }

        public static string Grade
        {
            get
            {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }

        public static string GradeDetails
        {
            get
            {
                return ResourceManager.GetString("GradeDetails", resourceCulture);
            }
        }

        public static string HeadOfDepartment
        {
            get
            {
                return ResourceManager.GetString("HeadOfDepartment", resourceCulture);
            }
        }

        public static string Help
        {
            get
            {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }

        public static string IdCard
        {
            get
            {
                return ResourceManager.GetString("IdCard", resourceCulture);
            }
        }

        public static string Index
        {
            get
            {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }

        public static string LastName
        {
            get
            {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }

        public static string Localization
        {
            get
            {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }

        public static string Name
        {
            get
            {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string New
        {
            get
            {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        public static string Next
        {
            get
            {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }

        public static string No
        {
            get
            {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        public static string Ok
        {
            get
            {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }

        public static string Pass
        {
            get
            {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }

        public static string PassedExams
        {
            get
            {
                return ResourceManager.GetString("PassedExams", resourceCulture);
            }
        }

        public static string PassedOne
        {
            get
            {
                return ResourceManager.GetString("PassedOne", resourceCulture);
            }
        }

        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        public static string Previous
        {
            get
            {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }

        public static string ProfessorDetails
        {
            get
            {
                return ResourceManager.GetString("ProfessorDetails", resourceCulture);
            }
        }

        public static string ProfessorList
        {
            get
            {
                return ResourceManager.GetString("ProfessorList", resourceCulture);
            }
        }

        public static string ProfessorName
        {
            get
            {
                return ResourceManager.GetString("ProfessorName", resourceCulture);
            }
        }

        public static string Professors
        {
            get
            {
                return ResourceManager.GetString("Professors", resourceCulture);
            }
        }

        public static string reasign
        {
            get
            {
                return ResourceManager.GetString("reasign", resourceCulture);
            }
        }

        public static string requestLabel
        {
            get
            {
                return ResourceManager.GetString("requestLabel", resourceCulture);
            }
        }

        public static string Save
        {
            get
            {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        public static string Search
        {
            get
            {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }

        public static string SelectHOD
        {
            get
            {
                return ResourceManager.GetString("SelectHOD", resourceCulture);
            }
        }

        public static string Semester
        {
            get
            {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }

        public static string Serbian
        {
            get
            {
                return ResourceManager.GetString("Serbian", resourceCulture);
            }
        }

        public static string ShowProfessors
        {
            get
            {
                return ResourceManager.GetString("ShowProfessors", resourceCulture);
            }
        }

        public static string StatusBarString
        {
            get
            {
                return ResourceManager.GetString("StatusBarString", resourceCulture);
            }
        }

        public static string Street
        {
            get
            {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }

        public static string StreetNumber
        {
            get
            {
                return ResourceManager.GetString("StreetNumber", resourceCulture);
            }
        }

        public static string StudentDetails
        {
            get
            {
                return ResourceManager.GetString("StudentDetails", resourceCulture);
            }
        }

        public static string StudentList
        {
            get
            {
                return ResourceManager.GetString("StudentList", resourceCulture);
            }
        }

        public static string Students
        {
            get
            {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }

        public static string SubjectDeletionWarning
        {
            get
            {
                return ResourceManager.GetString("SubjectDeletionWarning", resourceCulture);
            }
        }

        public static string SubjectDetails
        {
            get
            {
                return ResourceManager.GetString("SubjectDetails", resourceCulture);
            }
        }

        public static string SubjectId
        {
            get
            {
                return ResourceManager.GetString("SubjectId", resourceCulture);
            }
        }

        public static string SubjectList
        {
            get
            {
                return ResourceManager.GetString("SubjectList", resourceCulture);
            }
        }

        public static string TakingBoth
        {
            get
            {
                return ResourceManager.GetString("TakingBoth", resourceCulture);
            }
        }

        public static string Update
        {
            get
            {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        public static string UpdateDepartment
        {
            get
            {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }

        public static string UpdateProfessor
        {
            get
            {
                return ResourceManager.GetString("UpdateProfessor", resourceCulture);
            }
        }

        public static string UpdateStudent
        {
            get
            {
                return ResourceManager.GetString("UpdateStudent", resourceCulture);
            }
        }

        public static string UpdateSubject
        {
            get
            {
                return ResourceManager.GetString("UpdateSubject", resourceCulture);
            }
        }

        public static string Warning
        {
            get
            {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }

        public static string Year
        {
            get
            {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }

        public static string YearOfStudies
        {
            get
            {
                return ResourceManager.GetString("YearOfStudies", resourceCulture);
            }
        }

        public static string Yes
        {
            get
            {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string Yoe
        {
            get
            {
                return ResourceManager.GetString("Yoe", resourceCulture);
            }
        }

        public static string Subjects
        {
            get
            {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }

        public static string ExamGrades
        {
            get
            {
                return ResourceManager.GetString("ExamGrades", resourceCulture);
            }
        }

        public static string ShowStudents
        {
            get
            {
                return ResourceManager.GetString("ShowStudents", resourceCulture);
            }
        }

        public static string DeleteSubject
        {
            get
            {
                return ResourceManager.GetString("DeleteSubject", resourceCulture);
            }
        }

        public static string FirstYear
        {
            get
            {
                return ResourceManager.GetString("FirstYear", resourceCulture);
            }
        }

        public static string SecondYear
        {
            get
            {
                return ResourceManager.GetString("SecondYear", resourceCulture);
            }
        }

        public static string ThirdYear
        {
            get
            {
                return ResourceManager.GetString("ThirdYear", resourceCulture);
            }
        }

        public static string FourthYear
        {
            get
            {
                return ResourceManager.GetString("FourthYear", resourceCulture);
            }
        }

        public static string AdditionalFifthYear
        {
            get
            {
                return ResourceManager.GetString("AdditionalFifthYear", resourceCulture);
            }
        }

        public static string Summer
        {
            get
            {
                return ResourceManager.GetString("Summer", resourceCulture);
            }
        }

        public static string Winter
        {
            get
            {
                return ResourceManager.GetString("Winter", resourceCulture);
            }
        }

        public static string GovernmentBudget
        {
            get
            {
                return ResourceManager.GetString("GovernmentBudget", resourceCulture);
            }
        }

        public static string SelfFinancing
        {
            get
            {
                return ResourceManager.GetString("SelfFinancing", resourceCulture);
            }
        }



    }
}
